cbail:
  - "*"
lukebaker:
  - "*"
msalganik:
  - "*"
matnel:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
juhopaak:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
UMTti:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
joshua-a-becker:
  - "_data/2018/northwestern/"
  - "2018/northwestern/"
  - "_data/2018/chicago/"
  - "2018/chicago/"
allisonmorgan:
  - "_data/2018/boulder/"
  - "2018/boulder/"
visseho:
  - "_data/2018/capetown/"
  - "2018/capetown/"
ccgilroy:
  - "_data/2018/seattle/"
  - "2018/seattle/"
MariaYR:
  - "_data/2018/hunter-nyc/"
  - "2018/hunter-nyc/"
ausmani23:
  - "_data/2018/nyu-nyc/"
  - "2018/nyu-nyc/"
fmerhout:
  - "_data/2018/"
  - "assets/images"
  - "2018/"
marcone84:
  - "_data/2018/"
  - "2018/"
  - "assets/images"
taylorwhitten:
  - "_data/2018/"
  - "2018/"
  - "assets/images"
